version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: citel-teste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123455
