version: "3.9"

services:
  citel-postgres:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: citel-db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
