version: "3.9"

networks:
  citel-network:
    driver: bridge
  shared-db-network:
    external: true

services:
  citel-api:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
    ports:
      - "8181:8080"
    networks:
      - citel-network
      - shared-db-network # necessário apenas se o banco de dados estiver em outro container docker NA MESMA REDE
