spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD:${DB_PASS:}}

spring.jpa.show-sql=false

citel.config.tipo-importacao=LOCAL
