name: AWS Deploy - App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Build the API
        run: mvn clean package

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Agencia Citel API
          path: target

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit
