name: AWS Deploy - App

on:
  push:
    #branches: ["main"] // fazer deploy somente na branch production
    branches: ["production"] #Essa branch não existe ainda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Build the API
        run: mvn clean package -DDB_HOST=${{ secrets.DB_HOST }} -DDB_PORT=${{ secrets.DB_PORT }} -DDB_NAME=${{ secrets.DB_NAME }} -DDB_USER=${{ secrets.DB_USER }} -DDB_PASS=${{ secrets.DB_PASS }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Agencia Citel API
          path: target
  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit
